-- 코드를 입력하세요
# SELECT FIRST_HALF.FLAVOR
# FROM FIRST_HALF JOIN ICECREAM_INFO
# GROUP BY 
# # AND INGREDIENT_TYPE = "fruit_based";

SELECT A.FLAVOR
FROM FIRST_HALF AS A
LEFT JOIN ICECREAM_INFO AS B ON A.FLAVOR = B.FLAVOR
WHERE TOTAL_ORDER >= 3000
AND INGREDIENT_TYPE = "fruit_based"
ORDER BY TOTAL_ORDER DESC